// constants/kejadian.ts

export const namaList = [
  "Banjir rob",
  "Banjir bandang",
  "Banjir dan tanah longsor",
  "Banjir drainase dan selokan",
  "Banjir waduk",
  "Banjir genangan",
  "Tanggul jebol",
  "Longsor",
  "Gerakan tanah",
  "Gelombang pasang",
  "Abrasi Pantai",
  "Puting beliung",
  "Angin kencang",
  "Angin topan",
  "Hujan es",
  "Siklon tropis",
  "Suhu udara ekstrem",
  "Kekeringan meteorologis",
  "Kekeringan hidrologis",
  "Kekeringan pertanian",
  "Kebakaran hutan",
  "Kebakaran lahan",
  "Kebakaran lahan gambut",
  "Gempa tektonik",
  "Gempa vulkanik",
  "Gempabumi runtuhan",
  "Tsunami seismogenik",
  "Tsunami nonseismik",
  "Tsunami lokal",
  "Tsunami regional",
  "Tsunami jarak",
  "Tsunami meteorologi",
  "Mikrotsunami",
  "Awan panas guguran-aliran piroklastik guguran",
  "Awan panas-aliran piroklastik",
  "Banjir lahar",
  "Hujan abu vulkanik",
  "Gas vulkanik beracun",
  "Wabah penyakit",
  "Epidemi",
  "Kebakaran gedung dan pemukiman",
  "Kegagalan industri",
  "Kecelakaan industri",
  "Konflik Sosial",
  "Teror",
  "Kerusuhan Sosial",
];

export const jenisList = ["Bencana Alam", "Bencana NonAlam", "Bencana Sosial"];

export const kecList = [
  "Alak",
  "Kota Raja",
  "Kota Lama",
  "Oebobo",
  "Kelapa Lima",
  "Maulafa",
];

export const kelList = [
  "Alak",
  "Batuplat",
  "Fatufeto",
  "Mantasi",
  "Manulai II",
  "Manutapen",
  "Naioni",
  "Namosain",
  "Nunbaun Delha",
  "Nunbaun Sabu",
  "Nunhila",
  "Penkase Oeleta",
  "Kelapa Lima",
  "Lasiana",
  "Oesapa",
  "Oesapa Barat",
  "Oesapa Selatan",
  "Airnona",
  "Bakunase",
  "Bakunase II",
  "Fontein",
  "Kuanino",
  "Naikoten I",
  "Naikoten II",
  "Nunleu",
  "Air Mata",
  "Bonipoi",
  "Fatubesi",
  "Lai-lai Bisi Kopan",
  "Merdeka",
  "Nefonaek",
  "Oeba",
  "Pasir Panjang",
  "Solor",
  "Tode Kisar",
  "Belo",
  "Fatukoa",
  "Kolhua",
  "Maulafa",
  "Naikolan",
  "Naimata",
  "Oepura",
  "Penfui",
  "Sikumana",
  "Fatululi",
  "Kayu Putih",
  "Liliba",
  "Oebobo",
  "Oebufu",
  "Oetete",
  "Tuak Daun Merah",
];

export const numericFields = [
  // B.3 korban manusia
  "aml",
  "amp",
  "dwsml",
  "dwsmp",
  "lnml",
  "lnmp",
  "tml",
  "tmp",
  "ahl",
  "ahp",
  "dwshl",
  "dwshp",
  "lnhl",
  "lnhp",
  "thl",
  "thp",
  "alkl",
  "alkp",
  "dwsll",
  "dwslp",
  "lnll",
  "lnlp",
  "tll",
  "tlp",
  "atl",
  "atp",
  "dwstl",
  "dwstp",
  "lntl",
  "lntp",
  "ttl",
  "ttp",
  "aul",
  "aup",
  "dwsul",
  "dwsup",
  "lnul",
  "lnup",
  "tul",
  "tup",
  // B.4 pertanian
  "sawah",
  "txsawah",
  "lahan",
  "txlahan",
  "kebun",
  "txkebun",
  "hutan",
  "txhutan",
  "kolam",
  "txkolam",
  // B.4 kios & pabrik
  "kb",
  "ks",
  "kr",
  "ktrd",
  "txkios",
  "pb",
  "ps",
  "pr",
  "ptrd",
  "txpabrik",
  // B.5 prasarana
  "txair",
  "txlampu",
  "txkom",
  "txiri",
  "txjln",
  "txtrans",
  "txbbm",
  "jb",
  "js",
  "jr",
  "jtrd",
  "txjembatan",
  // B.6 rumah
  "rmhb",
  "rmhs",
  "rmhr",
  "rmhtrd",
  "txrmh",
  // B.7 pelayanan dasar
  "skob",
  "skos",
  "skor",
  "skotrd",
  "txsko",
  "rib",
  "ris",
  "rir",
  "ritrd",
  "txri",
  "faskesb",
  "faskess",
  "faskesr",
  "faskestrd",
  "txfaskes",
  "ktrb",
  "ktrs",
  "ktrr",
  "ktrtrd",
  "txktr",
  "psrb",
  "psrs",
  "psrr",
  "psrtrd",
  "txpsr",
];

export const numericDefaults = Object.fromEntries(
  numericFields.map((k) => [k, "0"])
);
